apiVersion: v1
kind: ConfigMap
metadata:
  name: site-forwarder-config
  namespace: og-edge
data:
  MQTT_BROKER_URL: mqtt://mosquitto.og-edge.svc.cluster.local:1883
  KAFKA_BOOTSTRAP_SERVERS: kafka.og-core.svc.cluster.local:9092
  STORE_BUFFER_PATH: /data/site-forwarder/buffer.db
  SITE_ID: site-alpha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-forwarder
  namespace: og-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-forwarder
  template:
    metadata:
      labels:
        app: site-forwarder
    spec:
      containers:
        - name: site-forwarder
          image: ghcr.io/replace-me/og-site-forwarder:stable
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: site-forwarder-config
          volumeMounts:
            - name: data
              mountPath: /data/site-forwarder
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          emptyDir: {}

